### Test Ping
GET http://localhost:3000/api


### Check Renew Token
GET http://localhost:3000/api/auth/auto-renew
Content-Type: application/json

### Login Head Nurse
# @name login
POST http://localhost:3000/api/dashboard/login
Content-Type: application/json
Accept: application/json

{
  "email": "kepala_perawat@mdjamil.com",
  "password": "kepala_perawat_picu"
}



### Login Nurse
# @name login
POST http://localhost:3000/api/nurse/login
Content-Type: application/json

{
  "email": "budi.nurse@mdjamil.com",
  "password": "perawat123"
}


### Register Nurse
POST http://localhost:3000/api/nurse/add
Content-Type: application/json

{
  "name": "Rani",
  "email": "rani@example.com",
  "password": "secret123"
}


### Get All Nurse
GET http://localhost:3000/api/nurse
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}


### Register Patient
POST http://localhost:3000/api/pasienCreate
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}

{
  "name": "Ghazy",
  "medicalRecordNumber": "1307011204002001",
  "birthDate": "1990-01-02",
  "bedNumber": 515,
  "gender": "LAKI_LAKI",
  "bradenQ": 12,
  "status": "ACTIVE"
}


### Get All Patients
GET http://localhost:3000/api/pasiens
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}


### Get Patient by ID
GET http://localhost:3000/api/pasien/cmgxfwpc6000064q0860inz4r
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}


### Update Patient by ID
PUT http://localhost:3000/api/pasien/cmgxfwpc6000064q0860inz4r
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}

{
  "name": "Ghazy",
  "nik": "1307123010020001",
  "birthDate": "1990-01-02",
  "bedNumber": 1,
  "gender": "LAKI_LAKI",
  "bradenQ": 10,
  "status": "NON_ACTIVE"
}


### Delete Patient by ID
DELETE http://localhost:3000/api/pasien/cmgt5heai000c64nwk61rt212
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}


### Create Patient Handle (Assign Patient)
# Membuat assignment pasien baru ke perawat + history awal
POST http://localhost:3000/api/patient-handle
Authorization: Bearer {{login.response.body.data.accessToken}}
Accept: application/json
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="patientId"

cmh8tl3pw0002648gmlt5vj6y
--MyBoundary
Content-Disposition: form-data; name="bradenQ"

15
--MyBoundary
Content-Disposition: form-data; name="needsManualReposition"

true
--MyBoundary
Content-Disposition: form-data; name="status"

ACTIVE
--MyBoundary
Content-Disposition: form-data; name="dekubitus"

false
--MyBoundary
Content-Disposition: form-data; name="foto"; filename="awal.jpg"
Content-Type: image/jpeg

< ./test-assets/awal.jpg
--MyBoundary--


### Get All Patient Handles
GET http://localhost:3000/api/patient-handles
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}


### Get Patient Handle by Nurse ID
GET http://localhost:3000/api/patient-handles/by-nurse/cmgt5hea5000764nwow3vxjuj
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}


### Get Patient History (All)
GET http://localhost:3000/api/patient-histories
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}


### Get Patient History by Patient ID
GET http://localhost:3000/api/patient-histories/by-patient/cmgxg3jt5000164ess9svo7b1
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}


### Get Nurse History
GET http://localhost:3000/api/nurse-histories
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}


### Get Nurse History by Nurse ID
GET http://localhost:3000/api/nurse-history/cmgt5hea5000764nwow3vxjuj
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}


### Get Nurse History Dropdown by Name
GET http://localhost:3000/api/nurse-history/id-option?q=SitiAisyah
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}


### Create Reposisi History
# Catat tindakan reposisi pasien berikutnya
# Otomatis menambahkan log di tabel ReposisiHistory
# dan memperbarui "nextRepositionTime" di PatientHandle
POST http://localhost:3000/api/reposisi
Authorization: Bearer {{login.response.body.data.accessToken}}
Accept: application/json
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="patientId"

cmgt5heag000b64nw8xmhx5tg
--MyBoundary
Content-Disposition: form-data; name="bradenQ"

12
--MyBoundary
Content-Disposition: form-data; name="position"

Miring kiri 30 derajat
--MyBoundary
Content-Disposition: form-data; name="foto"; filename="reposisi.jpg"
Content-Type: image/jpeg

< ./test-assets/reposisi.jpg
--MyBoundary--


### Create Reposisi (Tanpa Foto)
# Jika tidak ada bukti foto reposisi
POST http://localhost:3000/api/reposisi
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}

{
  "patientId": "cmgt5heag000b64nw8xmhx5tg",
  "bradenQ": 13,
  "position": "Terlentang"
}


### Get All Reposisi History
# Ambil semua catatan reposisi dari tabel ReposisiHistory
GET http://localhost:3000/api/reposisis
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}


### Get Reposisi History by Patient ID
# (opsional) jika nanti kamu tambahkan endpoint khusus by patientId
GET http://localhost:3000/api/patient-histories/by-patient/cmgt5heag000b64nw8xmhx5tg
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}
