### Test Ping
GET http://localhost:3000/api


### Login Head Nurse
# @name login
POST http://localhost:3000/api/dashboard/login
Content-Type: application/json
Accept: application/json

{
  "email": "kepala_perawat@mdjamil.com",
  "password": "kepala_perawat_picu"
}

### Login Nurse
# @name login
POST http://localhost:3000/api/nurse/login
Content-Type: application/json

{
  "email": "john.doe@email.com",
  "password": "12345678"
}

### Register Nurse
POST http://localhost:3000/api/nurse/add
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@email.com",
  "password": "12345678"
}

### Register Patient
POST http://localhost:3000/api/pasienCreate
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

{
  "name": "Ghazy",
  "nik": "1307011204002001",
  "birthDate": "1990-01-02",
  "bedNumber": 1,
  "gender": "LAKI_LAKI",
  "bradenQ": 12,
  "status": "ACTIVE"
}


### Get All Patients
GET http://localhost:3000/api/pasiens
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

### Get Patient by ID
GET http://localhost:3000/api/pasien/cmgg9ukrj0001648o7kqh3s74
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}


### Update Patient by ID
PUT http://localhost:3000/api/pasien/cmgg9ni7v0000648ozw9ujqag
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

{
  "name": "Jane Doe",
  "nik": "1307123010020001",
  "birthDate": "1990-01-01",
  "bedNumber": 1,
  "gender": "PEREMPUAN",
  "bradenQ": 12,
  "status": "NON_ACTIVE"
}

### Delete Patient by ID
DELETE http://localhost:3000/api/pasien/cmgg9ni7v0000648ozw9ujqag
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

### Create Patient Handle and History
POST http://localhost:3000/api/patient-handle
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

{
  "patientId": "cmghlw4z4000064fcm954n0oh",
  "bradenQ": 12,
  "foto": "http://example.com/foto.jpg",
  "status": "ACTIVE"
}

### Get All Patient Handles
GET http://localhost:3000/api/patient-handles
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

### Get Patient Handle by ID
GET http://localhost:3000/api/patient-handle/cmgg9ni7v0000648ozw9ujqag
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}