### Test Ping
GET http://localhost:3000/api


### Login Head Nurse
# @name login
POST http://localhost:3000/api/dashboard/login
Content-Type: application/json
Accept: application/json

{
  "email": "kepala_perawat@mdjamil.com",
  "password": "kepala_perawat_picu"
}

### Login Nurse
# @name login
POST http://localhost:3000/api/nurse/login
Content-Type: application/json

{
  "email": "john.nurse@mdjamil.com",
  "password": "perawat123"
}

### Register Nurse
POST http://localhost:3000/api/nurse/add
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@email.com",
  "password": "12345678"
}

### Register Patient
POST http://localhost:3000/api/pasienCreate
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}

{
  "name": "Ghazy",
  "nik": "1307011204002001",
  "birthDate": "1990-01-02",
  "bedNumber": 1,
  "gender": "LAKI_LAKI",
  "bradenQ": 12,
  "status": "ACTIVE"
}


### Get All Patients
GET http://localhost:3000/api/pasiens
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}

### Get Patient by ID
GET http://localhost:3000/api/pasien/cmgxfwpc6000064q0860inz4r
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}


### Update Patient by ID
PUT http://localhost:3000/api/pasien/cmgxfwpc6000064q0860inz4r
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}

{
  "name": "Ghazy",
  "nik": "1307123010020001",
  "birthDate": "1990-01-02",
  "bedNumber": 1,
  "gender": "LAKI_LAKI",
  "bradenQ": 10,
  "status": "NON_ACTIVE"
}

### Delete Patient by ID
DELETE http://localhost:3000/api/pasien/cmgt5heai000c64nwk61rt212
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}

### Create Patient Handle and History
POST http://localhost:3000/api/patient-handle
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}

{
  "patientId": "cmgxfwpc6000064q0860inz4r",
  "bradenQ": 12,
  "foto": "http://example.com/foto.jpg",
  "status": "ACTIVE"
}

### Get All Patient Handles
GET http://localhost:3000/api/patient-handles
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}

### Get Patient Handle by ID
GET http://localhost:3000/api/patient-handle/cmgxg3jt5000164ess9svo7b1
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}

### Get Patient History 
GET http://localhost:3000/api/patient-histories
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}

### Get Patient History by Patient ID
GET http://localhost:3000/api/patient-histories/by-patient/cmgxg3jt5000164ess9svo7b1
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}

### Get Nurse History
GET http://localhost:3000/api/nurse-histories
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}

### Get Nurse History By nurse Id
GET http://localhost:3000/api/nurse-histories/by-nurse/cmghmjire0000644c3bstfy83
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.accessToken}}





